# Generated by Django 4.2.4 on 2023-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="publico_alvo",
            field=models.CharField(default="Todos os publicos", max_length=255),
        ),
    ]
