# Generated by Django 4.2.4 on 2023-08-20 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="tipo_evento",
            new_name="tipos_evento",
        ),
    ]
