# Generated by Django 4.2.4 on 2023-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0003_alter_evento_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="bairro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="rua",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipos_evento",
            field=models.ManyToManyField(
                blank=True, null=True, to="eventos.tipoevento"
            ),
        ),
    ]
