# Generated by Django 4.2.4 on 2023-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
