# Generated by Django 4.2.4 on 2023-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.SmallIntegerField(default=0),
        ),
    ]
