# Generated by Django 4.2.4 on 2023-09-18 19:13

import CalendarioEventos.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_usuario_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/usuarios_perfil"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[CalendarioEventos.utils.utils.valida_cpf],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.SmallIntegerField(blank=True, default=0, max_length=30),
        ),
    ]
