# Generated by Django 4.2.4 on 2023-09-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_usuario_foto_perfil_alter_usuario_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
